server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: FoodOrderingApp-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurantdb
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
      sql: debug
      type:
        descriptor:
          sql: trace